import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "build"))

import saltro_py


PI = 3.14159265358979323846
DEG2RAD = PI / 180.0
SEC_PER_CENTURY = 36525.0 * 86400.0

DT_SECONDS = 10.0
SIM_SECONDS = 1000.0
N = int(SIM_SECONDS / DT_SECONDS) + 1
TUMBLE_STOP_THRESHOLD = 0.5 * DEG2RAD

# These are the exact five Monte Carlo cases generated by the C++
# std::mt19937-based test. Python's MT19937 stream does not match
# std::mt19937 seeding semantics here, so we pin the sampled satellites and
# initial states directly to keep the Python mirror identical in behavior.
CASES = [
    {
        "J": np.diag([1.1014272494027633, 1.6799760005725943, 1.3556967553739445]),
        "mtqs": [
            ([0.9884173443124189, 0.07112170865640907, 0.1340628808439463], 0.4),
            ([0.045409544892441485, -0.9376111008812915, 0.3447076975305803], 0.37808879348020064),
            ([-0.8859863901037904, 0.4516164133644171, 0.10521754478562179], 0.4),
        ],
        "rws": [
            ([0.2123310648805654, 0.24693591043698992, -0.9454830379352874], 0.008476307767511897, 0.002, 0.16),
            ([-0.8420829879301381, 0.1395995969873982, 0.5209685153246852], 0.008065595689252294, 0.002, 0.15149465360825387),
            ([-0.5867653727433032, 0.7364365399373056, 0.33670108404129284], 0.007575056187946056, 0.002, 0.10090425788125786),
        ],
        "x0": [-0.04712446238865915, 0.12784358588804717, -0.021665212214293138, 0.9097100081737518, -0.17007629531264123, 0.19842610826843224, -0.3226899973018753, 0.0, 0.0, 0.0],
    },
    {
        "J": np.diag([1.7541321781761681, 1.5394697174625598, 1.9681454185899609]),
        "mtqs": [
            ([-0.24817605399368678, -0.6803974358792046, 0.6895418591159831], 0.4),
            ([0.6862249730455723, -0.70634522742632, -0.17370004623103613], 0.2847327431935569),
            ([-0.7399262795508728, -0.46521096655402183, -0.48588872947196105], 0.4),
        ],
        "rws": [
            ([-0.22015536012056816, 0.5515385671776607, -0.8045724493952027], 0.00957837854441823, 0.002, 0.11722663023233577),
            ([0.31726319429388516, -0.5793081898056136, -0.7508302649537935], 0.008488556767755563, 0.002, 0.12427352048817546),
            ([0.27856299922485833, -0.01797553697900384, -0.960249725609525], 0.009469115983228298, 0.002, 0.1109854907983641),
        ],
        "x0": [-0.03611041607279108, -0.06708929280700564, 0.05928853121828884, 0.846829378326341, 0.5206172601965532, -0.10615311033380495, 0.023857693839019596, 0.0, 0.0, 0.0],
    },
    {
        "J": np.diag([0.8485767120652206, 0.762111206669526, 0.8137653349224922]),
        "mtqs": [
            ([0.606267076146091, 0.24860479299978333, -0.7554044541031016], 0.34582714096821304),
            ([-0.8340586164987355, -0.30684834442013764, -0.45846517618117527], 0.3632920188576969),
        ],
        "rws": [
            ([-0.18873435714457534, -0.12055404668867782, -0.9746004639133967], 0.004705434517168567, 0.002, 0.11467479364982823),
            ([0.682725062182271, -0.26172536419780307, 0.6821922919556785], 0.004507688297997796, 0.002, 0.1511821037039302),
        ],
        "x0": [-0.05857900811077154, 0.01854001397109643, -0.1609514683364528, 0.9242836624762278, 0.3464844655709266, 0.14714255149182798, -0.06322417210240566, 0.0, 0.0],
    },
    {
        "J": np.diag([1.3336485004613252, 1.7325700804463968, 1.2418032825820173]),
        "mtqs": [
            ([-0.6408282384962457, -0.7432973286739197, 0.19195897981603807], 0.3694330995230272),
            ([0.33806998051329046, -0.08509590481337843, 0.9372659042447538], 0.30759379457512476),
            ([-0.7591993715318548, 0.06079913620140216, -0.6480121752735826], 0.27811365572276864),
        ],
        "rws": [
            ([0.29878428714860766, -0.6845675676208164, 0.6649023951790349], 0.005784691931973958, 0.002, 0.1091740926909434),
            ([0.8386332523724136, -0.35160776062840665, 0.41601232034778107], 0.01, 0.002, 0.11156907384103384),
        ],
        "x0": [0.07601008411189085, -0.07385086248747898, -0.05946945070201624, 0.4072325267647089, 0.05774144489374621, -0.1410702286134893, -0.9005147335193084, 0.0, 0.0],
    },
    {
        "J": np.diag([0.22738213878491137, 1.3575888773106344, 1.3564520616159921]),
        "mtqs": [
            ([0.19788467625763076, -0.9774828277071815, 0.07327329963898949], 0.3329554295304014),
            ([-0.1127947559074214, 0.0172804004665833, 0.9934680320974096], 0.362543425577664),
        ],
        "rws": [
            ([0.6362863980683486, 0.5994399757973673, -0.48560409290826484], 0.0041221616271702594, 0.002, 0.11566970626897964),
            ([-0.5626280452771818, -0.4175977409750643, -0.7134856756796879], 0.004753949716923096, 0.002, 0.12551962293546284),
        ],
        "x0": [0.09457226478014719, 0.06005430204802473, 0.016156828312391944, 0.9509967854960976, 0.006638776430607624, -0.19393310450105392, -0.24073012192531507, 0.0, 0.0],
    },
]


def make_satellite_case(case):
    settings = saltro_py.PlannerSettings()
    settings.init_traj.initcontroller = 2
    settings.disturbances.plan_for_aero = False
    settings.disturbances.plan_for_gg = False
    settings.disturbances.plan_for_srp = False
    settings.disturbances.plan_for_prop = False
    settings.disturbances.plan_for_gendist = False
    settings.disturbances.plan_for_resdipole = False
    settings.num_passes = 1
    settings.passes[0].dt = DT_SECONDS

    satellite = saltro_py.Satellite(case["J"], settings)
    for axis, max_dipole in case["mtqs"]:
        satellite.addMTQ(np.array(axis, dtype=float), float(max_dipole))
    for axis, max_torque, rw_J, h_max in case["rws"]:
        satellite.addRW(np.array(axis, dtype=float), float(max_torque), float(rw_J), 0.0, float(h_max))

    return settings, satellite, np.array(case["x0"], dtype=float)


def make_constant_environment():
    jtime = np.zeros(N, dtype=float)
    q_goal = np.zeros((4, N), dtype=float)
    boresight = np.zeros((3, N), dtype=float)
    R = np.zeros((3, N), dtype=float)
    V = np.zeros((3, N), dtype=float)
    B = np.zeros((3, N), dtype=float)
    S = np.zeros((3, N), dtype=float)
    rho = np.zeros(N, dtype=float)

    B_const = np.array([2.2e-5, -1.6e-5, 3.1e-5], dtype=float)

    for k in range(N):
        t_sec = float(k) * DT_SECONDS
        jtime[k] = 0.25 + t_sec / SEC_PER_CENTURY
        q_goal[0, k] = 1.0
        boresight[:, k] = np.array([1.0, 0.0, 0.0], dtype=float)
        B[:, k] = B_const

    return jtime, q_goal, boresight, R, V, B, S, rho


def test_integratedbdotcontroller_warm_start_monte_carlo_detumbles_randomized_satellites():
    jtime, q_goal, boresight, R, V, B, S, rho = make_constant_environment()

    for sample, case in enumerate(CASES):
        settings, satellite, x0 = make_satellite_case(case)

        ok, X, U = saltro_py.warm_start(
            settings,
            satellite,
            x0,
            jtime,
            q_goal,
            boresight,
            R,
            V,
            B,
            S,
            rho,
        )

        assert ok

        initial_w = float(np.linalg.norm(x0[saltro_py.Satellite.AV_INDEX:saltro_py.Satellite.AV_INDEX + 3]))
        final_w = float(np.linalg.norm(X[saltro_py.Satellite.AV_INDEX:saltro_py.Satellite.AV_INDEX + 3, N - 1]))

        assert np.isfinite(final_w), (
            f"sample={sample} nMTQ={satellite.numMTQ} nRW={satellite.numRW} "
            f"initial_w={initial_w} final_w={final_w} Jdiag={np.diag(case['J'])}"
        )
        assert final_w <= TUMBLE_STOP_THRESHOLD, (
            f"sample={sample} nMTQ={satellite.numMTQ} nRW={satellite.numRW} "
            f"initial_w={initial_w} final_w={final_w} Jdiag={np.diag(case['J'])}"
        )
        assert final_w < initial_w, (
            f"sample={sample} nMTQ={satellite.numMTQ} nRW={satellite.numRW} "
            f"initial_w={initial_w} final_w={final_w} Jdiag={np.diag(case['J'])}"
        )
